export const ROUTES = {
  home: "/",
  importerStart: "/importer/start",
  verify: "/verify",
  verifyRepresentative: "/verify/representative",
  packages: "/packages",
  payments: "/payments",
  paymentsCheckout: "/payments/checkout",
  paymentsSuccess: "/payments/success",
  paymentsFailed: "/payments/failed",
  paymentsManual: "/payments/manual",
  invoices: "/invoices",
  refunds: "/refunds",
  refundsRequest: "/refunds/request",
  fms: "/fms",
  fmsApply: "/fms/apply",
  fmsApplicationUpdate: "/fms/application-update",
  fmsChinaProcurementAgent: "/fms/china-procurement-agent",
  fmsChinaSourcingJobs: "/fms/china-sourcing-jobs",
  fmsFactoryMatchSpecialist: "/fms/factory-match-specialist",
  fmsLogin: "/fms/login",
  contact: "/contact",
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  authRoleSelect: "/auth/role-select",
  authOtp: "/auth/otp",
  authInvite: "/auth/invite",
  authConfirmed: "/auth/confirmed",
  authSecurity: "/auth/security",
  learn: "/learn",
  learnImportFromChinaToPakistan: "/learn/import-from-china-to-pakistan",
  learnFindChineseFactories: "/learn/find-chinese-factories",
  learnAvoidMiddlemenChinaImports: "/learn/avoid-middlemen-china-imports",
  learnVerifyProductsBeforeShipping: "/learn/verify-products-before-shipping",
  admin: "/admin",
  adminLogin: "/admin/login",
  adminFms: "/admin/fms",
  adminPayments: "/admin/payments",
  adminRefunds: "/admin/refunds",
  adminFactorySubmissions: "/admin/factory-submissions",
  adminEvidence: "/admin/evidence",
  adminReportFeedback: "/admin/report-feedback",
  adminFactories: "/admin/factories",
  adminFactoryReviewQueue: "/admin/factories/review-queue",
  adminMessages: "/admin/messages",
  adminNotifications: "/admin/notifications",
  adminRepresentatives: "/admin/representatives",
  superAdmin: "/super-admin",
  superAdminFmsApplications: "/super-admin/fms-applications",
  superAdminLogin: "/super-admin/login",
  superAdminNotifications: "/super-admin/notifications",
  superAdminRoleControls: "/super-admin/role-controls",
  superAdminUsers: "/super-admin/users",
  projectManager: "/project-manager",
  projectManagerDashboard: "/project-manager/dashboard",
  projectManagerLogin: "/project-manager/login",
  projectManagerNotifications: "/project-manager/notifications",
  projectManagerProjects: "/project-manager/projects",
  agent: "/agent",
  agentLogin: "/agent/login",
  agentDashboard: "/agent/dashboard",
  agentLeads: "/agent/leads",
  agentCommissions: "/agent/commissions",
  agentTraining: "/agent/training",
  agentNotifications: "/agent/notifications",
  factory: "/factory",
  factoriesExportToPakistan: "/factories/export-to-pakistan",
  factoriesFindPakistaniBuyers: "/factories/find-pakistani-buyers",
  factoriesPartnership: "/factories/partnership",
  factoryLogin: "/factory/login",
  factorySignup: "/factory/signup",
  fmsDashboard: "/fms/dashboard",
  fmsAssignments: "/fms/assignments",
  fmsEarnings: "/fms/earnings",
  fmsOpportunities: "/fms/opportunities",
  fmsOpportunityChinaSourcingJobs: "/fms/opportunities/china-sourcing-jobs",
  fmsOpportunityPakistaniImporters:
    "/fms/opportunities/work-with-pakistani-importers",
  fmsAcademy: "/fms/academy",
  fmsMessages: "/fms/messages",
  fmsNotifications: "/fms/notifications",
  importerMessages: "/importer/messages",
  importerDashboard: "/importer/dashboard",
  importerNotifications: "/importer/notifications",
  importerProjects: "/importer/projects",
  importerReports: "/importer/reports",
} as const;

export const RESERVED_ROUTES = [
  ROUTES.admin,
  ROUTES.superAdmin,
  ROUTES.projectManager,
  ROUTES.agent,
  ROUTES.factory,
  ROUTES.fmsDashboard,
  ROUTES.importerDashboard,
  ROUTES.importerProjects,
  ROUTES.importerReports,
] as const;

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];

export const brand = {
  name: "ChinaPak ImportHub",
  domain: "chinapakimporthub.com",
  tagline: "Direct China Factory Access for Pakistani Importers",
  urduLine: "چین کی فیکٹری سے پاکستان کے کاروبار تک",
  promise:
    "Help Pakistani importers access suitable Chinese factories, review factory-side product evidence before shipment, reduce unnecessary middlemen, and import from China without traveling to China.",
  colors: {
    primary: "#0B1F3A",
    secondary: "#138A4A",
    accent: "#C99A2E",
    background: "#F7F9FC",
    text: "#111827",
    mutedText: "#6B7280",
    warning: "#F59E0B",
    error: "#DC2626",
  },
  locales: [
    { code: "ur", label: "اردو", direction: "rtl" },
    { code: "en", label: "English", direction: "ltr" },
    { code: "zh-CN", label: "简体中文", direction: "ltr" },
  ],
  defaultLocale: "en",
  navigation: {
    primary: [
      {
        label: "How It Works",
        englishLabel: "How It Works",
        href: "/how-it-works",
      },
      { label: "پیکجز", englishLabel: "Packages", href: ROUTES.packages },
      { label: "Learn", englishLabel: "Learn", href: ROUTES.learn },
      { label: "Verify Us", englishLabel: "Verify Us", href: ROUTES.verify },
      { label: "FMS", englishLabel: "FMS", href: ROUTES.fms },
      { label: "Contact", englishLabel: "Contact", href: ROUTES.contact },
    ],
    auth: [
      { label: "لاگ اِن", englishLabel: "Login", href: ROUTES.login },
      {
        label: "اکاؤنٹ بنائیں",
        englishLabel: "Sign up",
        href: ROUTES.signup,
      },
    ],
  },
  packages: [
    {
      id: "factory-discovery",
      name: "Factory Discovery",
      urduName: "فیکٹری ڈسکوری",
      price: "PKR 18,000",
      bestFor: "PKR 100k-300k import budgets",
      factoryOptions: "Up to 3 factory options",
      deliveryTarget: "5-7 business days",
      summary:
        "For importers who want a practical first look at suitable Chinese factory options.",
      includes: [
        "Import Project ID setup",
        "Product requirement review",
        "Admin-reviewed factory shortlist",
      ],
    },
    {
      id: "factory-match-plus",
      name: "Factory Match Plus",
      urduName: "فیکٹری میچ پلس",
      price: "PKR 35,000",
      bestFor: "PKR 300k-700k import budgets",
      factoryOptions: "Up to 5 factory options",
      deliveryTarget: "7-10 business days",
      summary:
        "For importers who need stronger comparison and factory-side product evidence.",
      includes: [
        "Factory match support",
        "Factory-side photos/videos",
        "Comparison-ready admin summary",
      ],
    },
    {
      id: "import-partner",
      name: "Import Partner",
      urduName: "امپورٹ پارٹنر",
      price: "PKR 75,000",
      bestFor: "PKR 700k-1.5m+ import budgets",
      factoryOptions: "8-10 factory options",
      deliveryTarget: "10-15 business days",
      summary:
        "For importers who need deeper project support and a wider factory comparison.",
      includes: [
        "Priority project review",
        "Wider factory option search",
        "Secure project tracking trail",
      ],
    },
  ],
  routes: ROUTES,
} as const;

export type PackagePlan = (typeof brand.packages)[number];
